services:
  visionx-go2rtc:
    image: alexxit/go2rtc:latest
    container_name: visionx-go2rtc
    ports:
      - "1984:1984"       # Web UI and API
      - "8654:8554"       # RTSP restream
      - "8555:8555/tcp"   # WebRTC
      - "8555:8555/udp"   # WebRTC
    volumes:
      - ./docker/go2rtc/go2rtc.yaml:/config/go2rtc.yaml
    restart: unless-stopped


  mailpit:
    image: axllent/mailpit
    container_name: visionx-mailpit
    profiles:
      - dev
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000


  visionx-redis:
    image: redis:8-alpine
    container_name: visionx-redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server --save "" --appendonly no