"""Add health status enum

Revision ID: 49b4e55015e7
Revises: 694f237fcbf8
Create Date: 2026-07-24 12:07:16.145343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49b4e55015e7'
down_revision: Union[str, Sequence[str], None] = '694f237fcbf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('online', 'degraded', 'offline', name='healthstatusenum').create(op.get_bind(), checkfirst=True)
    op.alter_column('camera_health_checks', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('online', 'degraded', 'offline', name='healthstatusenum'),
               postgresql_using='status::healthstatusenum',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('camera_health_checks', 'status',
               existing_type=sa.Enum('online', 'degraded', 'offline', name='healthstatusenum'),
               type_=sa.VARCHAR(),
               postgresql_using='status::varchar',
               existing_nullable=False)
    sa.Enum(name='healthstatusenum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
