"""add password reset token model

Revision ID: 5fa90c4b3851
Revises: 7b6f8a4e9351
Create Date: 2026-08-05 18:22:56.596605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa90c4b3851'
down_revision: Union[str, Sequence[str], None] = '7b6f8a4e9351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_password_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_reset_password_tokens_expires_at'), 'reset_password_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_reset_password_tokens_user_id'), 'reset_password_tokens', ['user_id'], unique=False)
    op.alter_column('cameras', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('snapshots', 'created_at',
                server_default=sa.text('now()'))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_changed_at')
    op.alter_column('cameras', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('snapshots', 'created_at',
                server_default=None)
    op.drop_index(op.f('ix_reset_password_tokens_user_id'), table_name='reset_password_tokens')
    op.drop_index(op.f('ix_reset_password_tokens_expires_at'), table_name='reset_password_tokens')
    op.drop_table('reset_password_tokens')
    # ### end Alembic commands ###
