"""add camera main and sub rtsp urls

Revision ID: 694f237fcbf8
Revises: aca8f818d480
Create Date: 2026-07-02 22:48:33.457486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '694f237fcbf8'
down_revision: Union[str, Sequence[str], None] = 'aca8f818d480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('rtsp_main_url', sa.String(), nullable=False))
    op.add_column('cameras', sa.Column('rtsp_sub_url', sa.String(), nullable=False))
    op.drop_column('cameras', 'rtsp_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('rtsp_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('cameras', 'rtsp_sub_url')
    op.drop_column('cameras', 'rtsp_main_url')
    # ### end Alembic commands ###
